import Layout from 'layout'
import Head from 'next/head'
import TopBar from 'components/top-bar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>detikcom - clone</title>
        <meta content='Generated by create next app' name='description' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      <TopBar />
      Hello
    </div>
  )
}

Home.getLayout = (page) => (
  <Layout>
    {page}
  </Layout>
)
