import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>detikcom - clone</title>
        <meta content='Generated by create next app' name='description' />
        <link href='/favicon.ico' rel='icon' />
      </Head>
      Hello
    </div>
  )
}
